server:
  port: ${PORT:5000}

spring:
  sql:
    init:
      mode: always
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  mandatory-file-encoding: UTF-8
  messages:
    encoding: UTF-8
  datasource:
    initialization-mode: always
    sqlScriptEncoding: UTF-8
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost/ml_shipping}
    username: postgres
    password: root
    hikari:
      connectionTimeout: 30000
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect

ml-shipping:
  deposit-limit: 100